import axios from 'axios';
import Head from 'next/head';
import AwsS3 from '@uppy/aws-s3';
import { StatusBar, FileInput } from '@uppy/react';
import Uppy from '@uppy/core';
import '@uppy/core/dist/style.min.css';
import '@uppy/file-input/dist/style.min.css';
import '@uppy/status-bar/dist/style.min.css';
import { useState } from 'react';

export default function Home() {
  const [uppyInfo, setUppyInfo] = useState('Upload file (max 300MB)');
  const uppy = new Uppy({
    id: 'upload',
    autoProceed: true,
    restrictions: {
      maxFileSize: 314572800,
      maxNumberOfFiles: 1,
      minNumberOfFiles: null,
      allowedFileTypes: ['video/*'],
    },
  })
    .use(AwsS3, {
      async getUploadParameters(file) {
        return axios(`/api/wasabi-presigned-url?file=${file.name}`).then((response) => {
          return {
            method: 'PUT',
            url: response.data.url,
            fields: [],
          };
        });
      },
    })
    .on('complete', (result) => {
      if (result.successful) {
        // updateMedia('upload', result.successful[0].uploadURL);
        setUppyInfo(`Upload complete! File: ${result.successful[0].name}`);
      } else {
        setUppyInfo(`Upload error: ${result.failed}`);
      }
      uppy.close();
    });

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-full min-h-screen space-y-10 text-white bg-gray-700">
        <p>{uppyInfo}</p>
        <FileInput uppy={uppy} pretty />
        <div className="w-full">
          <StatusBar uppy={uppy} hideUploadButton showProgressDetails />
        </div>
      </div>
    </div>
  );
}
